gallery/urls.py
from django.urls import path

from . import views

app_name = 'gallery'

urlpatterns = [
    path('', views.index, name='index'),
    path('portfolio/tile/', views.PortfolioTile.as_view(), name='portfolio.tile'),
    path('portfolio/user/', views.PortfolioUser.as_view(), name='portfolio.user'),
    path('portfolio/create_user/', views.PortfolioCreate.as_view(), name='portfolio.create'),
    path('portfolio/create_project/<project_pk>/', views.PortfolioCreateForProject.as_view(), name='portfolio.create_for_project'),
    path('portfolio/create_team/<team_pk>/', views.PortfolioCreateForTeam.as_view(), name='portfolio.create_for_team'),
    path('portfolio/create_work/<work_pk>/', views.PortfolioCreateForWork.as_view(), name='portfolio.create_for_work'),
    path('portfolio/<pk>/', views.PortfolioDetail.as_view(), name='portfolio.detail'),
    path('portfolio/<pk>/update/', views.PortfolioUpdate.as_view(), name='portfolio.update'),
    path('portfolio/<pk>/friend/', views.portfolio_toggle_friend, name='portfolio.friend'),
    path('portfolio/<pk>/like/', views.portfolio_toggle_like, name='portfolio.like'),
    path('portfolio/<pk>/share/', views.portfolio_toggle_share, name='portfolio.share'),
    path('portfolio/<pk>/report/', views.portfolio_report, name='portfolio.report'),
    path('portfolio/<pk>/delete/', views.PortfolioDelete.as_view(), name='portfolio.delete'),
    path('portfolio/<pk>/comment/create/', views.CommentCreate.as_view(), name='comment.create'),
    path('portfolio/<portfolio_pk>/comment/<pk>/delete/', views.CommentDelete.as_view(), name='comment.delete'),
]

job/urls.py
from django.urls import path

from . import views

app_name = 'job'

urlpatterns = [
    path('', views.index, name='index'),
    path('work/tile/', views.WorkTile.as_view(), name='work.tile'),
    path('work/user/', views.WorkUser.as_view(), name='work.user'),
    path('work/create/', views.WorkCreate.as_view(), name='work.create'),
    path('work/<pk>/', views.WorkDetail.as_view(), name='work.detail'),
    path('work/<pk>/update/', views.WorkUpdate.as_view(), name='work.update'),
    path('work/<pk>/delete/', views.WorkDelete.as_view(), name='work.delete'),
    path('portfolio/<pk>/friend/', views.work_toggle_friend, name='work.friend'),
    path('portfolio/<pk>/bookmark/', views.work_toggle_bookmark, name='work.bookmark'),
    path('portfolio/<pk>/apply/', views.work_toggle_apply, name='work.apply'),
    path('portfolio/<pk>/share/', views.work_toggle_share, name='work.share'),
    path('work/<pk>/comment/create/', views.CommentCreate.as_view(), name='comment.create'),
    path('work/<work_pk>/comment/<pk>/delete/', views.CommentDelete.as_view(), name='comment.delete'),
]

myartworks/urls.py
from django.conf.urls.static import static
from django.urls import path
from django.conf import settings
from django.urls import include
from django.contrib import admin


urlpatterns = [
    path('', include(('common.urls', 'common'), namespace='common')),
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('classification/', include(('classification.urls', 'classification'), namespace='classification')),
    path('gallery/', include(('gallery.urls', 'gallery'), namespace='gallery')),
    path('job/', include(('job.urls', 'job'), namespace='job')),
    path('messagebox/', include(('messagebox.urls', 'messagebox'), namespace='messagebox')),
    path('resume/', include(('resume.urls', 'resume'), namespace='resume')),
    path('group/', include(('group.urls', 'group'), namespace='group')),
    path('organization/', include(('organization.urls', 'organization'), namespace='organization')),
]

urlpatterns += [
    path('search/', include(('haystack.urls', 'haystack'), namespace='search')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Error page
handler400 = 'common.views.handler400'
handler403 = 'common.views.handler403'
handler404 = 'common.views.handler404'
handler405 = 'common.views.handler405'
handler500 = 'common.views.handler500'

gallery/models.py
import time
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from classification.models import Category
from group.models import Project
from organization.models import Team
from job.models import Work

from taggit.managers import TaggableManager


class Portfolio(models.Model):
    """
    Portfolio class
    """
    image = models.ImageField(upload_to=''.join(['gallery/', time.strftime('%Y%m%d'), '/']))
    resource = models.FileField(upload_to='gallery/resource/', blank=True, null=True)
    title = models.CharField(max_length=50)
    content = models.CharField(max_length=200)
    category = models.ManyToManyField(Category)
    writer = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, null=True, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, null=True, on_delete=models.CASCADE)
    work = models.ForeignKey(Work, null=True, on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True)
    updated_time = models.DateTimeField(auto_now_add=True)
    comment_count = models.IntegerField(default=0)
    like_count = models.IntegerField(default=0)
    share_count = models.IntegerField(default=0)
    report_count = models.IntegerField(default=0)
    tags = TaggableManager()

    class Meta:
        pass

    def __str__(self):
        return "{}".format(self.id)

    def get_absolute_url(self):
        return reverse('gallery:portfolio.tile')

    def categories(self):
        return ", ".join([category.name for category in self.category.all()])


class Comment(models.Model):
    """
    Comment class
    """
    portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    writer = models.ForeignKey(User, related_name='gallery_comments', on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        pass

    def __str__(self):
        return "{}".format(self.id)

    def get_absolute_url(self):
        return reverse('gallery:portfolio.detail', kwargs={'pk': str(self.portfolio.pk)})

    def save(self, *args, **kwargs):
        super(Comment, self).save(*args, **kwargs)


class Like(models.Model):
    """
    Like class
    """
    portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE)
    writer = models.ForeignKey(User, related_name='gallery_likes', on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        pass

    def __str__(self):
        return "{}".format(self.id)

    def get_absolute_url(self):
        return reverse('gallery:portfolio.detail', kwargs={'pk': str(self.portfolio.pk)})


class Share(models.Model):
    """
    Share class
    """
    portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE)
    writer = models.ForeignKey(User, related_name='gallery_shares', on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        pass

    def __str__(self):
        return "{}".format(self.id)

    def get_absolute_url(self):
        return reverse('gallery:portfolio.detail', kwargs={'pk': str(self.portfolio.pk)})

    def save(self, *args, **kwargs):
        super(Share, self).save(*args, **kwargs)


class Report(models.Model):
    """
    Report class
    """
    portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE)
    writer = models.ForeignKey(User, related_name='gallery_reports', on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        pass

    def __str__(self):
        return "{}".format(self.id)

    def get_absolute_url(self):
        return reverse('gallery:portfolio.detail', kwargs={'pk': str(self.portfolio.pk)})

    def save(self, *args, **kwargs):
        super(Report, self).save(*args, **kwargs)

job/views.py
import logging
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import resolve, reverse_lazy
from django.shortcuts import get_object_or_404, redirect
from django.utils.translation import ugettext_lazy as _
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from core.mixins import WriterOnlyMixin

from accounts.models import Friend

from .models import Work, Comment, Bookmark, Apply, Share
from .forms import WorkCreateForm, WorkUpdateForm, CommentForm


logger = logging.getLogger(__name__)


def index(request):
    return redirect('job:work.tile')


class WorkTile(LoginRequiredMixin, ListView):
    """
    Retrieve Work List
    """
    model = Work
    context_object_name = 'work_list'
    http_method_names = ['get']
    template_name = 'job/work_list_tile.html'
    paginate_by = 9

    def get_queryset(self):
        work_list = Work.objects.all().order_by('-created_time')
        return work_list

    def get_context_data(self, **kwargs):
        context = super(WorkTile, self).get_context_data(**kwargs)
        context['title'] = _(resolve(self.request.path).app_name.capitalize())

        return context


class WorkUser(LoginRequiredMixin, ListView):
    """
    Retrieve Work List
    """
    model = Work
    context_object_name = 'work_list'
    http_method_names = ['get']
    template_name = 'job/work_list_user.html'
    paginate_by = 9

    def get_queryset(self):
        work_list = Work.objects.filter(writer=self.request.user).order_by('-created_time')
        return work_list

    def get_context_data(self, **kwargs):
        context = super(WorkUser, self).get_context_data(**kwargs)
        context['title'] = _(resolve(self.request.path).app_name.capitalize())
        context['work_form'] = WorkCreateForm
        context['comment_form'] = CommentForm

        return context


class WorkCreate(LoginRequiredMixin, CreateView):
    """
    Create Work
    """
    model = Work
    form_class = WorkCreateForm
    http_method_names = ['get', 'post', ]
    template_name = 'job/work_form_create.html'
    success_url = reverse_lazy('job:work.tile')

    def form_valid(self, form):
        work = form.save(commit=False)
        work.writer = self.request.user
        work.save()
        form.save_m2m()
        messages.success(self.request, _('Your work was created successfully.'))
        return super(WorkCreate, self).form_valid(form)

    def form_invalid(self, form):
        return super(WorkCreate, self).form_invalid(form)

    def get_success_url(self):
        return reverse_lazy('accounts:profile.detail', args=(self.request.user.username,))


class WorkDetail(LoginRequiredMixin, DetailView):
    """
    Detail Work
    """
    model = Work
    context_object_name = 'work'
    http_method_names = ['get']

    def get_context_data(self, **kwargs):
        context = super(WorkDetail, self).get_context_data(**kwargs)
        context['comment_form'] = CommentForm
        return context


class WorkUpdate(WriterOnlyMixin, UpdateView):
    """
    Update Work
    """
    model = Work
    form_class = WorkUpdateForm
    context_object_name = 'work'
    http_method_names = ['get', 'post', ]
    template_name = 'job/work_form_update.html'

    def form_valid(self, form):
        work = form.save(commit=False)
        work.writer = self.request.user
        work.save()
        form.save_m2m()
        messages.success(self.request, _('Your work was updated successfully.'))
        return super(WorkUpdate, self).form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, _('Your work was not updated!'))
        return super(WorkUpdate, self).form_invalid(form)


class WorkDelete(WriterOnlyMixin, DeleteView):
    """
    Delete Work
    """
    model = Work
    context_object_name = 'work'
    http_method_names = ['get', 'post']
    success_url = reverse_lazy('job:work.tile')


def work_toggle_friend(request, **kwargs):
    context = {}
    request_user = User.objects.get(pk=request.user.pk)
    work = Work.objects.get(pk=kwargs["pk"])
    try:
        friend = Friend.objects.get(writer=request_user, friend=work.writer)
        friend.delete()
        context['class'] = 'fa fa-chain-broken'
    except Friend.DoesNotExist:
        friend = Friend(writer=request_user, friend=work.writer)
        friend.save()
        context['class'] = 'fa fa-link'
    return JsonResponse(context)


def work_toggle_bookmark(request, **kwargs):
    context = {}
    work = Work.objects.get(pk=kwargs["pk"])
    writer = User.objects.get(pk=request.user.pk)
    try:
        bookmark = Bookmark.objects.get(work=work, writer=writer)
        bookmark.delete()
        if work.bookmark_count > 0:
            work.bookmark_count -= 1
            work.save()
        context['class'] = 'fa fa-bookmark-o'
    except Bookmark.DoesNotExist:
        bookmark = Bookmark(work=work, writer=writer)
        bookmark.save()
        work.bookmark_count += 1
        work.save()
        context['class'] = 'fa fa-bookmark'
    context['count'] = work.bookmark_count
    context['span'] = ''.join(['#', 'badge-bookmark-', str(work.pk)])
    return JsonResponse(context)


def work_toggle_apply(request, **kwargs):
    context = {}
    work = Work.objects.get(pk=kwargs["pk"])
    writer = User.objects.get(pk=request.user.pk)
    try:
        apply = Apply.objects.get(work=work, writer=writer)
        apply.delete()
        if work.apply_count > 0:
            work.apply_count -= 1
            work.save()
        context['class'] = 'fa fa-flag-o'
    except Apply.DoesNotExist:
        apply = Apply(work=work, writer=writer)
        apply.save()
        work.apply_count += 1
        work.save()
        context['class'] = 'fa fa-flag'
    context['count'] = work.apply_count
    context['span'] = ''.join(['#', 'badge-apply-', str(work.pk)])
    return JsonResponse(context)


def work_toggle_share(request, **kwargs):
    context = {}
    work = Work.objects.get(pk=kwargs["pk"])
    writer = User.objects.get(pk=request.user.pk)
    try:
        share = Share.objects.get(work=work, writer=writer)
        share.delete()
        if work.share_count > 0:
            work.share_count -= 1
            work.save()
        context['class'] = 'fa fa-share-square-o'
    except Share.DoesNotExist:
        share = Share(work=work, writer=writer)
        share.save()
        work.share_count += 1
        work.save()
        context['class'] = 'fa fa-share-square'
    context['count'] = work.share_count
    context['span'] = ''.join(['#', 'badge-share-', str(work.pk)])
    return JsonResponse(context)


class CommentList(LoginRequiredMixin, ListView):
    """
    Comment List
    """
    model = Comment
    context_object_name = 'comment_list'
    http_method_names = ['get']
    paginate_by = 9

    def get_queryset(self):
        comment_list = Comment.objects.all().order_by('-created_time')
        return comment_list

    def get_context_data(self, **kwargs):
        context = super(CommentList, self).get_context_data(**kwargs)
        work = get_object_or_404(Work, pk=self.kwargs.get('pk'))
        context['work'] = work
        return context


class CommentCreate(LoginRequiredMixin, CreateView):
    """
    Create Comment
    """
    model = Comment
    form_class = CommentForm
    http_method_names = ['get', 'post', ]
    template_name = 'job/comment_form.html'

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.work = get_object_or_404(Work, pk=self.kwargs.get('pk'))
        comment.writer = self.request.user
        comment.save()
        messages.success(self.request, _('Your comment was created successfully.'))
        return super(CommentCreate, self).form_valid(form)

    def form_invalid(self, form):
        return super(CommentCreate, self).form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super(CommentCreate, self).get_context_data(**kwargs)
        work = get_object_or_404(Work, pk=self.kwargs.get('pk'))
        context['work'] = work
        return context


class CommentDelete(WriterOnlyMixin, DeleteView):
    """
    Delete Comment
    """
    model = Comment
    http_method_names = ['get', 'post']

    def get_success_url(self):
        return reverse_lazy('job:work.detail', args=(self.object.work.id,))

    def delete(self, request, *args, **kwargs):
        messages.success(request, _('Your comment was deleted successfully.'))
        return super(CommentDelete, self).delete(request, *args, **kwargs)

gallery/templates/gallery/base_site.html
{% extends "common/base.html" %}
{% load i18n static %}{% load humanize %}
{% block title %}{{ title|default:_('Home') }} | {{ site_title|default:_('MyArtworks') }}{% endblock %}

gallery/templates/gallery/comment_form.html
{% extends "gallery/base_site.html" %}
{% load i18n static %}{% load humanize %}
{% load widget_tweaks %}

{% block content %}
    <div class="col-lg-offset-2 col-lg-8">
        <form class="form-horizontal" action="{% url 'gallery:comment.create' pk=portfolio.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group {% if form.content.errors %}has-error{% endif %}">{{ form.content }}</div>
            <a class="btn btn-default" href="{% url 'gallery:portfolio.detail' pk=portfolio.pk %}"><i class="fa fa-times" aria-hidden="true"></i> {% trans 'Cancel' %}</a>
            <input class="btn btn-theme" type="submit" value="{% trans 'Submit' %}"/>
        </form>
    </div>
{% endblock %}

gallery/templates/gallery/portfolio_form_create.html
{% load i18n static %}{% load humanize %}
{% load widget_tweaks %}
<div class="modal fade" role="dialog" id="id_portfolio_create_modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="{% url 'gallery:portfolio.create' %}" method="post" enctype="multipart/form-data" id="id_form_create">
                {% csrf_token %}
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">{% trans 'Create Portfolio' %}</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group filebox preview-image">
                        <input class="upload-name form-control" value="{% trans 'Choose file' %}" style="width:300px;">
                        <label class="btn btn-default" for="{{ form.image.id_for_label }}">{{ form.image.label }}</label>
                        {{ form.image|add_class:"upload-hidden" }}
                    </div>
                    <div class="form-group {% if form.resource.errors %}has-error{% endif %}">{{ form.resource }}</div>
                    <div class="form-group {% if form.title.errors %}has-error{% endif %}">{{ form.title }}</div>
                    <div class="form-group {% if form.content.errors %}has-error{% endif %}">{{ form.content }}</div>
                    <div class="form-group {% if form.tags.errors %}has-error{% endif %}">{{ form.tags }}</div>
                </div>
                <div class="modal-footer">
                    <a class="btn btn-default" href="{% url 'gallery:portfolio.user' %}" data-dismiss="modal">
                        <i class="fa fa-times" aria-hidden="true"></i> {% trans 'Cancel' %}
                    </a>
                    <input class="btn btn-theme" type="submit" value="{% trans 'Submit' %}"/>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="{% static 'common/js/playanetworks.js' %}"></script>
<script type="text/javascript">
    $("#id_form_create").submit(function(event){
       if(!$("#id_content").val()) {
           $("#id_content").attr("placeholder", "Type some contents here");
           $("#id_content").parent().addClass("has-error");
           event.preventDefault();
       }
    });
</script>

gallery/templates/gallery/portfolio_list_user.html
{% extends "gallery/base_site.html" %}
{% load i18n static %}{% load humanize %}
{% load gallery_filters %}

{% block content %}
<div class="col-lg-offset-2 col-lg-8">
    {% if user.is_authenticated %}
        <a href="{% url 'gallery:portfolio.create' %}" class="btn btn-default btn-lg btn-block" id="id_portfolio_create"><i class="fa fa-plus" aria-hidden="true"></i> {% trans 'Create Portfolio' %}</a><br/>
    {% endif %}

    {% if is_paginated %}
    <ul class="pager">
        {% if page_obj.has_previous %}
            <li><a href="{% url 'gallery:portfolio.user' %}?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}
        <li><a href="#">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
        {% if page_obj.has_next %}
            <li><a href="{% url 'gallery:portfolio.user' %}?page={{ page_obj.next_page_number }}">Next</a></li>
        {% endif %}
    </ul>
    {% endif %}

    {% for portfolio in portfolio_list %}
        <div class="panel panel-default">
            <div class="panel-heading">
                {% if user.is_authenticated %}
                    {% if portfolio.writer != request.user %}
                    <a href="{% url 'gallery:portfolio.friend' pk=portfolio.pk %}"><i class="{% is_portfolio_friend portfolio username=request.user.username %}" aria-hidden="true" id="i-friend-{{ portfolio.pk }}"></i></a>
                    {% endif %}
                    {% if portfolio.writer.profile.status == 'A' %}
                        &nbsp;<i class="fa fa-unlock" aria-hidden="true"></i>
                    {% else %}
                        &nbsp;<i class="fa fa-lock" aria-hidden="true"></i>
                    {% endif %}
                {% endif %}
                    <a href="{% url 'accounts:profile.detail' username=portfolio.writer.username %}">{{ portfolio.writer }}</a> on {{ portfolio.created_time|naturaltime }}
                {% if user.is_authenticated and portfolio.writer == request.user %}
                    &nbsp;<a href="{% url 'gallery:portfolio.update' pk=portfolio.id %}" id="id_portfolio_update"><i class="fa fa-cog" aria-hidden="true" id="i-update-{{ portfolio.pk }}"></i></a>
                    &nbsp;<a href="{% url 'gallery:portfolio.delete' pk=portfolio.id %}" id="id_portfolio_delete"><i class="fa fa-trash" aria-hidden="true" id="i-delete-{{ portfolio.pk }}"></i></a>
                {% endif %}
            </div>
            <div class="panel-body">
                <a href="{% url 'gallery:portfolio.detail' pk=portfolio.pk %}"><img src="{{ portfolio.image.url }}" alt="{{ portfolio.title }}" width="100%"></a>
                <br/>
                {{ portfolio.categories }}
                <br/>
                <p>
                    &nbsp;&nbsp;<i class="{% has_portfolio_comment portfolio username=request.user.username %}" aria-hidden="true"></i> <span class="badge" id="badge-comment-{{ portfolio.pk }}">{{ portfolio.comment_set.all|length }}</span>
                    &nbsp;&nbsp;<a href="{% url 'gallery:portfolio.like' pk=portfolio.pk %}"><i class="{% has_portfolio_like portfolio username=request.user.username %}" aria-hidden="true"></i></a> <span class="badge" id="badge-like-{{ portfolio.pk }}">{{ portfolio.like_count }}</span>
                    &nbsp;&nbsp;<a href="{% url 'gallery:portfolio.share' pk=portfolio.pk %}"><i class="{% has_portfolio_share portfolio username=request.user.username %}" aria-hidden="true"></i></a> <span class="badge" id="badge-share-{{ portfolio.pk }}">{{ portfolio.share_count }}</span>
                    &nbsp;&nbsp;<a href="{% url 'gallery:portfolio.report' pk=portfolio.pk %}" class="btn btn-link pull-right" id="id_portfolio_report"><strong>...</strong></a>
                </p>
                <a href="{% url 'accounts:profile.detail' username=portfolio.writer.username %}">{{ portfolio.writer }}</a>
                {% if portfolio.resource %}
                    <a href="{{ portfolio.resource.url }}"><i class="fa fa-folder" aria-hidden="true"></i></a>
                {% else %}
                    <i class="fa fa-folder-o" aria-hidden="true"></i>
                {% endif %}
                <br/>
                {{ portfolio.content }}<br/>
                <hr class="featurette-divider">
                {% if user.is_authenticated %}
                    <form class="form-horizontal" action="{% url 'gallery:comment.create' pk=portfolio.pk %}"
                          method="post" enctype="multipart/form-data" id="form-comment">
                        {% csrf_token %}
                        <div class="{% if comment_form.content.errors %}has-error{% endif %}" id="id_div_content">
                            {{ comment_form.content }}
                        </div>
                    </form>
                {% endif %}<br/>
                {% for comment in portfolio.comment_set.all %}
                    <a href="{% url 'accounts:profile.detail' username=comment.writer.username %}">{{ comment.writer.username }}</a>
                    {{ comment.content }}
                    {% if comment.writer == request.user %}
                        &nbsp;<a href="{% url 'gallery:comment.delete' portfolio_pk=portfolio.pk pk=comment.pk %}" id="id_portfolio_comment_delete"><i class="fa fa-trash" aria-hidden="true"></i></a>
                    {% endif %}
                    <br/>
                {% empty %}
                    <p class="text-muted"><i>No comment exists yet.</i></p>
                {% endfor %}

            </div>
        </div>
    {% empty %}
        <p class="text-muted"><i>No portfolio exists yet.</i></p>
    {% endfor %}



    {% if is_paginated %}
    <ul class="pager">
        {% if page_obj.has_previous %}
            <li><a href="{% url 'gallery:portfolio.user' %}?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}
        <li><a href="#">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
        {% if page_obj.has_next %}
            <li><a href="{% url 'gallery:portfolio.user' %}?page={{ page_obj.next_page_number }}">Next</a></li>
        {% endif %}
    </ul>
    {% endif %}
</div>
{% endblock %}


{% block extrascript %}
<script type="text/javascript">
    $("i[id*='i-friend-']").click(function(event){
        event.preventDefault();
        var element = this;
        $.ajax({
            method: "POST",
            url: $(this).parents().attr("href"),
            contentType: 'application/json; charset=utf-8',
            dataType: 'json',
            data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
            success: function(data, textStatus, jqXHR){
                $(element).removeClass();
                $(element).addClass(data.class);
            },
            error: function(jqXHR, textStatus, errorThrown) {
                console.log("error >>> " + textStatus);
            }
        }).done(function(){
            console.log("done");
        });
    });

    $("p a i.fa").click(function(event){
        event.preventDefault();
        var element = this;
        $.ajax({
            method: "POST",
            url: $(this).parents().attr("href"),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            data: { "csrfmiddlewaretoken": "{{ csrf_token }}"},
            success: function(data, textStatus, jqXHR){
                $(data.span).text(data.count);
                $(element).removeClass();
                $(element).addClass(data.class);
            },
            error: function(jqXHR, textStatus, errorThrown) {
                console.log("error >>> " + textStatus);
            }
        }).done(function(){
            console.log("done");
        });
    });

    $("#form-comment").submit(function(event){
       if(!$("#id_content").val()) {
           $("#id_content").attr("placeholder", "Type some contents here");
           $("#id_div_content").addClass("has-error");
           event.preventDefault();
       }
    });

    $("[id^='id_portfolio']").click(function(event){
        event.preventDefault();
        var element = this;
        $.ajax({
            method: "GET",
            url: $(this).attr("href"),
            contextType: "application/json; charset=utf-8",
            dataType: "html",
            data: {},
            success: function(data, textStatus, jqXHR){
                $("#id_row_modal").children().replaceWith(data);
                $("#"+$(element).attr("id")+"_modal").modal();
                // $("#id_portfolio_create_modal").modal();
            },
            error: function(jqXHR, textStatus, errorThrown){
                console.log("error >>> " + textStatus);
            }
        }).done(function(){
            console.log("done");
        });
    });
</script>
{% endblock %}