accounts/urls.py
from django.urls import path
from django.contrib import auth

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('search/', views.search, name='search'),
    #path('<username>/', views.detail, name='detail'),
    path('join/<username>/', views.join_group, name='join'),
    path('groups/<username>/', views.groups, name='groups'),
    path('password_change/', views.password_change, name='password_change'),
    #path('password/reset/', auth.views.password_reset, {'post_reset_redirect': '/password/reset/done/'}, name='password_reset'),
    #path('password/reset/done/', auth.views.password_reset_done),
    #path('password/reset/<uid36>[0-9A-Za-z]+)-<token>.+)/', auth.views.password_reset_confirm, {'post_reset_redirect': '/password/done/'}, name='password_reset_confirm'),
    #path('password/done/', auth.views.password_reset_complete),
    path('friend/<username>/list/', views.FriendList.as_view(), name='friend.list'),
    path('friend/<username>/for_list/', views.FriendForList.as_view(), name='friend.list_for'),
    path('friend/<username>/create/', views.FriendCreate.as_view(), name='friend.create'),
    path('friend/<username>/<pk>/', views.FriendDetail.as_view(), name='friend.detail'),
    path('friend/<username>/<pk>/update/', views.FriendUpdate.as_view(), name='friend.update'),
    path('friend/<username>/<pk>/delete/', views.FriendDelete.as_view(), name='friend.delete'),
    path('profile/list/', views.ProfileList.as_view(), name='profile.list'),
    path('profile/<username>/', views.ProfileDetail.as_view(), name='profile.detail'),
    path('profile/<username>/update/', views.ProfileUpdate.as_view(), name='profile.update'),
    path('profile/<username>/friend/', views.profile_toggle_friend, name='profile.friend'),
    path('profile/<username>/credit/', views.profile_toggle_credit, name='profile.credit'),
]

job/urls.py
from django.urls import path

from . import views

app_name = 'job'

urlpatterns = [
    path('', views.index, name='index'),
    path('work/tile/', views.WorkTile.as_view(), name='work.tile'),
    path('work/user/', views.WorkUser.as_view(), name='work.user'),
    path('work/create/', views.WorkCreate.as_view(), name='work.create'),
    path('work/<pk>/', views.WorkDetail.as_view(), name='work.detail'),
    path('work/<pk>/update/', views.WorkUpdate.as_view(), name='work.update'),
    path('work/<pk>/delete/', views.WorkDelete.as_view(), name='work.delete'),
    path('portfolio/<pk>/friend/', views.work_toggle_friend, name='work.friend'),
    path('portfolio/<pk>/bookmark/', views.work_toggle_bookmark, name='work.bookmark'),
    path('portfolio/<pk>/apply/', views.work_toggle_apply, name='work.apply'),
    path('portfolio/<pk>/share/', views.work_toggle_share, name='work.share'),
    path('work/<pk>/comment/create/', views.CommentCreate.as_view(), name='comment.create'),
    path('work/<work_pk>/comment/<pk>/delete/', views.CommentDelete.as_view(), name='comment.delete'),
]

myartworks/urls.py
from django.conf.urls.static import static
from django.urls import path
from django.conf import settings
from django.urls import include
from django.contrib import admin


urlpatterns = [
    path('', include(('common.urls', 'common'), namespace='common')),
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('classification/', include(('classification.urls', 'classification'), namespace='classification')),
    path('gallery/', include(('gallery.urls', 'gallery'), namespace='gallery')),
    path('job/', include(('job.urls', 'job'), namespace='job')),
    path('messagebox/', include(('messagebox.urls', 'messagebox'), namespace='messagebox')),
    path('resume/', include(('resume.urls', 'resume'), namespace='resume')),
    path('group/', include(('group.urls', 'group'), namespace='group')),
    path('organization/', include(('organization.urls', 'organization'), namespace='organization')),
]

urlpatterns += [
    path('search/', include(('haystack.urls', 'haystack'), namespace='search')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Error page
handler400 = 'common.views.handler400'
handler403 = 'common.views.handler403'
handler404 = 'common.views.handler404'
handler405 = 'common.views.handler405'
handler500 = 'common.views.handler500'

accounts/models.py
import uuid, time
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from taggit.managers import TaggableManager


class Profile(models.Model):
    GENDER = (
        ('M', _('Male')),
        ('F', _('Female')),
    )
    STATUS = (
        ('A', _('Available')),
        ('O', _('Occupied')),
    )
    TYPE = (
        ('P', _('Personal')),
        ('C', _('Company')),
        ('G', _('Government')),
    )
    writer = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
    slug = models.UUIDField(default=uuid.uuid4, blank=True, editable=False)
    picture = models.ImageField('Profile picture',
                                upload_to=''.join(['profile_picture/', time.strftime('%Y%m%d'), '/']),
                                default='profile_picture/default.png',
                                blank=True,
                                null=True
                                )
    nick_name = models.CharField(max_length=128)
    gender = models.CharField(max_length=1, choices=GENDER, blank=True, null=True)
    birth_date = models.DateField(blank=True, null=True)
    phone_number = models.CharField(max_length=128, blank=True, null=True)
    bio = models.TextField("Bio", max_length=2048, blank=True, null=True)
    status = models.CharField(max_length=1, default='A', choices=STATUS)
    type = models.CharField(max_length=1, default='P', choices=TYPE)
    credit_count = models.IntegerField(default=0)
    tags = TaggableManager()

    class Meta:
        pass

    def __str__(self):
        return self.writer.username


class Friend(models.Model):
    """
    Friend class
    """
    writer = models.ForeignKey(User, related_name="accounts_friends", on_delete=models.CASCADE)
    friend = models.ForeignKey(User, related_name="accounts_friend_friends", on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        pass

    def __str__(self):
        return "{}:{}->{}".format(self.id, self.writer.username, self.friend.username)

    def get_absolute_url(self):
        return reverse('accounts:friend.detail', kwargs={'pk': str(self.friend.pk)})


class Credit(models.Model):
    """
    Credit class
    """
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    writer = models.ForeignKey(User, related_name='profile_credits', on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        pass

    def __str__(self):
        return "{}".format(self.id)

    def get_absolute_url(self):
        return reverse('accounts:credit.detail', kwargs={'pk': str(self.credit.pk)})

    def save(self, *args, **kwargs):
        super(Credit, self).save(*args, **kwargs)

job/models.py
import time
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from classification.models import Category
from group.models import Project
from organization.models import Team

from taggit.managers import TaggableManager


class Work(models.Model):
    """
    Work class
    """
    image = models.ImageField(upload_to=''.join(['job/', time.strftime('%Y%m%d'), '/']))
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=2048)
    category = models.ManyToManyField(Category)
    writer = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, null=True, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, null=True, on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True)
    updated_time = models.DateTimeField(auto_now_add=True)
    comment_count = models.IntegerField(default=0)
    bookmark_count = models.IntegerField(default=0)
    apply_count = models.IntegerField(default=0)
    share_count = models.IntegerField(default=0)
    tags = TaggableManager()

    class Meta:
        pass

    def __str__(self):
        return "{}".format(self.id)

    def get_absolute_url(self):
        return reverse('job:work.tile')

    def categories(self):
        return ", ".join([category.name for category in self.category.all()])


class Comment(models.Model):
    """
    Comment class
    """
    work = models.ForeignKey(Work, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    writer = models.ForeignKey(User, related_name='work_comments', on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        pass

    def __str__(self):
        return "{}".format(self.id)

    def get_absolute_url(self):
        return reverse('job:work.detail', kwargs={'pk': str(self.work.pk)})

    def save(self, *args, **kwargs):
        super(Comment, self).save(*args, **kwargs)


class Bookmark(models.Model):
    """
    Bookmark class
    """
    work = models.ForeignKey(Work, on_delete=models.CASCADE)
    writer = models.ForeignKey(User, related_name='work_bookmarks', on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        pass

    def __str__(self):
        return "{}".format(self.id)

    def get_absolute_url(self):
        return reverse('job:work.detail', kwargs={'pk': str(self.work.pk)})

    def save(self, *args, **kwargs):
        super(Bookmark, self).save(*args, **kwargs)


class Apply(models.Model):
    """
    Apply class
    """
    work = models.ForeignKey(Work, on_delete=models.CASCADE)
    writer = models.ForeignKey(User, related_name='work_applies', on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        pass

    def __str__(self):
        return "{}".format(self.id)

    def get_absolute_url(self):
        return reverse('job:work.detail', kwargs={'pk': str(self.work.pk)})

    def save(self, *args, **kwargs):
        super(Apply, self).save(*args, **kwargs)


class Share(models.Model):
    """
    Share class
    """
    work = models.ForeignKey(Work, on_delete=models.CASCADE)
    writer = models.ForeignKey(User, related_name='work_shares', on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        pass

    def __str__(self):
        return "{}".format(self.id)

    def get_absolute_url(self):
        return reverse('job:work.detail', kwargs={'pk': str(self.work.pk)})

    def save(self, *args, **kwargs):
        super(Share, self).save(*args, **kwargs)

accounts/forms.py
from django.contrib.auth.models import User
from django import forms
from taggit.forms import TagField, TagWidget
from core.widgets import BootstrapSelectInput, BootstrapTextInput, BootstrapTextarea
from .models import Profile, Friend


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username',
                  'first_name',
                  'last_name',
                  'email',
                  ]


class ProfileSimpleForm(forms.ModelForm):
    type = forms.ChoiceField(widget=forms.RadioSelect, choices=Profile.TYPE)
    nick_name = forms.CharField(widget=BootstrapTextInput(placeholder='Nick name'))
    class Meta:
        model = Profile
        fields = ['type',
                  'nick_name',
                  ]


class ProfileForm(forms.ModelForm):
    picture = forms.ClearableFileInput()
    type = forms.ChoiceField(widget=forms.RadioSelect, choices=Profile.TYPE)
    nick_name = forms.CharField(widget=BootstrapTextInput(placeholder='Nick name'))
    gender = forms.ChoiceField(widget=BootstrapSelectInput(), choices=Profile.GENDER)
    birth_date = forms.DateField(widget=BootstrapTextInput(placeholder='Birthday'))
    phone_number = forms.CharField(widget=BootstrapTextInput(attrs={'placeholder': '***-****-****'}), required=False)
    bio = forms.CharField(widget=BootstrapTextarea(placeholder='Biography'), required=False)
    status = forms.ChoiceField(widget=BootstrapSelectInput(), choices=Profile.STATUS)
    tags = TagField(widget=TagWidget(attrs={'class': 'form-control', 'placeholder': 'Tags'}))

    class Meta:
        model = Profile
        fields = ['picture',
                  'type',
                  'nick_name',
                  'gender',
                  'birth_date',
                  'phone_number',
                  'bio',
                  'tags'
                  ]


class FriendForm(forms.ModelForm):
    friend = forms.ModelChoiceField(widget=BootstrapSelectInput(), queryset=User.objects.all(), empty_label="(Nothing)")

    class Meta:
        model = Friend
        fields = ['friend']

job/forms.py
from django import forms
from taggit.forms import TagField, TagWidget
from core.widgets import BootstrapTextInput, BootstrapTextarea
from .models import Work, Comment


class WorkCreateForm(forms.ModelForm):
    """
    Work Create form
    """
    image = forms.ImageField(required=True)
    title = forms.CharField(widget=BootstrapTextInput(placeholder='Title'))
    description = forms.CharField(widget=BootstrapTextarea(placeholder='Description'))
    tags = TagField(widget=TagWidget(attrs={'class': 'form-control', 'placeholder': 'Tags'}))

    class Meta:
        model = Work
        fields = ['image', 'title', 'description', 'tags']


class WorkUpdateForm(forms.ModelForm):
    """
    Work Update form
    """
    description = forms.CharField(widget=BootstrapTextarea(placeholder='Description'))
    tags = TagField(widget=TagWidget(attrs={'class': 'form-control', 'placeholder': 'Tags'}))

    class Meta:
        model = Work
        fields = ['description', 'tags']


class CommentForm(forms.ModelForm):
    """
    Comment form
    """
    content = forms.CharField(widget=BootstrapTextInput(placeholder='Content'))

    class Meta:
        model = Comment
        fields = ['content', ]

accounts/templates/accounts/base_site.html
{% extends "common/base.html" %}
{% load i18n static %}{% load humanize %}


{% block title %}{{ title|default:_('Home') }} | {{ site_title|default:_('MyArtworks') }}{% endblock %}

accounts/templates/accounts/deleted.html
{% extends "common/base_site.html" %}
{% load i18n static %}{% load humanize %}


{% block content %}
<div>
    <a href="{% url 'common:index' %}">Index</a>
</div>
{% endblock %}

accounts/templates/accounts/friend_confirm_delete.html
{% extends "accounts/base_site.html" %}
{% load i18n static %}{% load humanize %}

{% block content_menu %}{% endblock %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    <h2>Are you sure you want to delete "{{ friend }}"?</h2>
    <a class="btn btn-default" href="{% url 'accounts:friend.detail' username=request.user.username pk=friend.pk %}"><i class="fa fa-times" aria-hidden="true"></i> {% trans 'Cancel' %}</a>
    <input class="btn btn-danger" type="submit" value="Confirm"/>
</form>
{% endblock %}

accounts/templates/accounts/friend_form.html
{% extends "accounts/base_site.html" %}
{% load i18n static %}{% load humanize %}
{% load widget_tweaks %}

{% block content_title %}<h1>{% trans 'Create Friend' %}</h1>{% endblock %}
{% block content_menu %}{% endblock %}

{% block content %}
    <div class="col-lg-offset-2 col-lg-8">
        <form class="form-horizontal" action="{% url 'accounts:friend.create' username=request.user.username %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">{{ form.friend }}</div>
            <input class="btn btn-theme" type="submit" value="{% trans 'Submit' %}"/>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends "common/base_site.html" %}
{% load i18n static %}{% load humanize %}

{% block content %}
<p>Your password has been set.  You may go ahead and log in now.</p>
<p><a href="{% url 'index' %}">Log in</a></p>
{% endblock %}

accounts/templates/accounts/profile_detail.html
{% extends "common/base_site.html" %}
{% load i18n static %}{% load humanize %}
{% load widget_tweaks %}
{% load accounts_filters %}
{% load gallery_filters %}

{% block content_title %}{% endblock %}
{% block content_menu %}{% endblock %}

{% block content %}


<div class="row">
    <div class="col-lg-offset-1 col-lg-3">
        <img class="img-circle" src="{{ profile.picture.url }}" alt="{{ profile }}" width="140" height="140">
    </div>
    <div class="col-lg-4">
        <h2>
            {% if user != profile.writer %}
            <a href="{% url 'accounts:profile.friend' username=profile.writer.username %}"><i class="{% is_profile_friend profile username=request.user.username %}" aria-hidden="true" id="id-friend-{{ profile.username }}"></i></a>
            {% endif %}
            {{ profile }}
            {% if user == profile.writer %}
            <a href="{% url 'resume:index' %}" class="btn btn-default">Resume</a>
            {% endif %}
        </h2>
        {{ profile.nick_name }} / {{ profile.get_type_display }} / {{ profile.get_status_display }}<br/>
        {% trans 'Portfolio' %} {{ portfolio_list|length }}{% trans 'EA' %} /
        {% if user == profile.writer %}
        &nbsp;<i class="fa fa-star-o" aria-hidden="true"></i> <span class="badge">{{ profile.credit_count }}</span>
        {% else %}
            &nbsp;<a href="{% url 'accounts:profile.credit' username=profile.writer.username %}">
                 <i class="{% has_profile_credit profile username=request.user.username %}" aria-hidden="true" id="id-credit-{{ profile.username }}"></i>
              </a>
              <span class="badge" id="badge-credit-{{ profile.writer.username }}">{{ profile.credit_count }}</span>
        {% endif %}
        <br/>
        {% for tag in profile.tags.all %}
            {{ tag.name }}
        {% empty %}
        {% endfor %}
        <br/>
          <div class="btn-group">
            <a href="{% url 'accounts:friend.list' username=profile.writer.username %}" class="btn btn-default" id="id_profile_friend_list">
                Following <span class="badge">{{ profile.writer.accounts_friends.all|length }}</span>
            </a>
            <a href="{% url 'accounts:friend.list_for' username=profile.writer.username %}" class="btn btn-default" id="id_profile_friend_list_for">
                Follower <span class="badge">{{ profile.writer.accounts_friend_friends.all|length }}</span>
            </a>
          </div>
        <p>

        </p>
    </div>
    <div class="col-lg-4"><br/>
        {% if user == profile.writer %}
        <div class="btn-group">
            <a href="{% url 'accounts:profile.update' username=user.username %}" class="btn btn-default">{% trans 'Edit Profile' %}</a>
            <a href="#" class="btn btn-default" id="dropdown-menu-a-setting"><i class="fa fa-cog" aria-hidden="true"></i> {% trans 'Settings' %}</a>
            <a href="{% url 'accounts:logout' %}" class="btn btn-default" id="dropdown-menu-a-logout"><i class="fa fa-sign-out" aria-hidden="true"></i> {% trans 'Log out' %}</a>
        </div><br/>
        {% endif %}
        {{ profile.bio }}
    </div>
</div>
<hr class="featurette-divider">
<div class="row">
    <div class="col-lg-4">
        {% if user == profile.writer %}
            <a href="{% url 'group:project.create' %}" class="btn btn-default btn-lg btn-block" id="id_project_create"><i class="fa fa-plus" aria-hidden="true"></i> {% trans 'Create Project' %}</a><br/>
        {% endif %}
        {% for project in project_list %}
            <i class="fa fa-circle-o" aria-hidden="true"></i>
            <a href="{% url 'group:project.detail' pk=project.pk %}">{{ project.name|truncatechars:20 }}</a>
            <br/>
        {% empty %}
        {% endfor %}
        <a href="{% url 'group:project.user' %}" class="btn btn-link">More &raquo;</a>
    </div>
    <div class="col-lg-4">
        {% if user == profile.writer %}
            <a href="{% url 'organization:team.create' %}" class="btn btn-default btn-lg btn-block" id="id_team_create"><i class="fa fa-plus" aria-hidden="true"></i> {% trans 'Create Team' %}</a><br/>
        {% endif %}
        {% for team in team_list %}
            <i class="fa fa-circle-o" aria-hidden="true"></i>
            <a href="{% url 'organization:team.detail' pk=team.pk %}">{{ team.name|truncatechars:20 }}</a>
            <br/>
        {% empty %}
        {% endfor %}
        <a href="{% url 'organization:team.user' %}" class="btn btn-link">More &raquo;</a>
    </div>
    <div class="col-lg-4">
        {% if user == profile.writer %}
            <a href="{% url 'job:work.create' %}" class="btn btn-default btn-lg btn-block" id="id_work_create"><i class="fa fa-plus" aria-hidden="true"></i> {% trans 'Create Work' %}</a><br/>
        {% endif %}
        {% for work in work_list %}
            <i class="fa fa-circle-o" aria-hidden="true"></i>
            <a href="{% url 'job:work.detail' pk=work.pk %}">{{ work.title|truncatechars:20 }}</a>
            <br/>
        {% empty %}
        {% endfor %}
        <a href="{% url 'job:work.user' %}" class="btn btn-link">More &raquo;</a>
    </div>
</div>
<hr class="featurette-divider">
<div class="row">
    <div class="col-lg-2">
        <h6>{% trans 'Project applied' %}</h6>
        {% for apply in project_apply %}
            <i class="fa fa-circle-o" aria-hidden="true"></i>
            <a href="{% url 'group:project.detail' pk=apply.project.pk %}">{{ apply.project.name|truncatechars:10 }}</a>
            <br/>
        {% empty %}
        {% endfor %}
    </div>
    <div class="col-lg-2">
        <h6>{% trans 'Team applied' %}</h6>
        {% for apply in team_apply %}
            <i class="fa fa-circle-o" aria-hidden="true"></i>
            <a href="{% url 'organization:team.detail' pk=apply.team.pk %}">{{ apply.team.name|truncatechars:10 }}</a>
            <br/>
        {% empty %}
        {% endfor %}
    </div>
    <div class="col-lg-2">
        <h6>{% trans 'Work applied' %}</h6>
        {% for apply in work_apply %}
            <i class="fa fa-circle-o" aria-hidden="true"></i>
            <a href="{% url 'job:work.detail' pk=apply.work.pk %}">{{ apply.work.title|truncatechars:10 }}</a>
            <br/>
        {% empty %}
        {% endfor %}
    </div>
    <div class="col-lg-2">
        <h6>{% trans 'Project bookmarked' %}</h6>
        {% for bookmark in project_bookmark %}
            <i class="fa fa-circle-o" aria-hidden="true"></i>
            <a href="{% url 'group:project.detail' pk=bookmark.project.pk %}">{{ bookmark.project.name|truncatechars:10 }}</a>
            <br/>
        {% empty %}
        {% endfor %}
    </div>
    <div class="col-lg-2">
        <h6>{% trans 'Team bookmarked' %}</h6>
        {% for bookmark in team_bookmark %}
            <i class="fa fa-circle-o" aria-hidden="true"></i>
            <a href="{% url 'organization:team.detail' pk=bookmark.team.pk %}">{{ bookmark.team.name|truncatechars:10 }}</a>
            <br/>
        {% empty %}
        {% endfor %}
    </div>
    <div class="col-lg-2">
        <h6>{% trans 'Work bookmarked' %}</h6>
        {% for bookmark in work_bookmark %}
            <i class="fa fa-circle-o" aria-hidden="true"></i>
            <a href="{% url 'job:work.detail' pk=bookmark.work.pk %}">{{ bookmark.work.title|truncatechars:10 }}</a>
            <br/>
        {% empty %}
        {% endfor %}
    </div>
</div>
<hr class="featurette-divider">
    {% if user == profile.writer %}
        <a href="{% url 'gallery:portfolio.create' %}" class="btn btn-default btn-lg btn-block" id="id_portfolio_create"><i class="fa fa-plus" aria-hidden="true"></i> {% trans 'Create Portfolio' %}</a><br/>
    {% endif %}

    {% for portfolio in portfolio_list %}
    {% if forloop.counter0|divisibleby:3 %}
    <!-- Content Row -->
    <div class="row">
    {% endif %}
        <div class="col-lg-4">
            <div class="list-group">
                <a href="{% url 'gallery:portfolio.detail' pk=portfolio.pk %}" class="list-group-item">
                    <h4 class="list-group-item-heading">
                        <img src="{{ portfolio.image.url }}" alt="{{ portfolio.title }}" width="100%">
                    </h4>
                    <p class="list-group-item-text">
                        {{ portfolio.description|linebreaks }}
                        <small>by {{ portfolio.writer }} on {{ portfolio.created_time|naturaltime }}</small><br/>
                        <span class="badge" id="badge-comment-{{ portfolio.pk }}"><i class="{% has_portfolio_comment portfolio username=request.user.username %}" aria-hidden="true"></i> {{ portfolio.comment_set.all|length }}</span>
                        <span class="badge" id="badge-apply-{{ portfolio.pk }}"><i class="{% has_portfolio_like portfolio username=request.user.username %}" aria-hidden="true"></i> {{ portfolio.apply_count }}</span>
                        <span class="badge" id="badge-share-{{ portfolio.pk }}"><i class="{% has_portfolio_share portfolio username=request.user.username %}" aria-hidden="true"></i> {{ portfolio.share_count }}</span>
                    </p>
                </a>
            </div>
        </div>
        <!-- /.col-md-4 -->
        {% if forloop.counter|divisibleby:3 or forloop.last %}
    </div>
    <!-- /.row -->
    {% endif %}
    {% empty %}
    <p>{% trans 'No item exists yet.' %}</p>
    {% endfor %}

{% endblock %}



{% block extrascript %}
<script type="text/javascript">
    $("[id^='id-friend']").click(function(event){
        event.preventDefault();
        var element = this;
        $.ajax({
            method: "POST",
            url: $(this).parents().attr("href"),
            contentType: 'application/json; charset=utf-8',
            dataType: 'json',
            data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
            success: function(data, textStatus, jqXHR){
                $(element).removeClass();
                $(element).addClass(data.class);
            },
            error: function(jqXHR, textStatus, errorThrown) {
                console.log("error >>> " + textStatus);
            }
        }).done(function(){
            console.log("done");
        });
    });

    $("[id^='id-credit']").click(function(event){
        event.preventDefault();
        var element = this;
        $.ajax({
            method: "POST",
            url: $(this).parents().attr("href"),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            data: { "csrfmiddlewaretoken": "{{ csrf_token }}"},
            success: function(data, textStatus, jqXHR){
                $(data.span).text(data.count);
                $(element).removeClass();
                $(element).addClass(data.class);
            },
            error: function(jqXHR, textStatus, errorThrown) {
                console.log("error >>> " + textStatus);
            }
        }).done(function(){
            console.log("done");
        });
    });

    $("#form-comment").submit(function(event){
       if(!$("#id_content").val()) {
           $("#id_content").attr("placeholder", "Type some contents here");
           $("#id_div_content").addClass("has-error");
           event.preventDefault();
       }
    });

    $("[id^='id_profile']").click(function(event){
        event.preventDefault();
        var element = this;
        $.ajax({
            method: "GET",
            url: $(this).attr("href"),
            contextType: "application/json; charset=utf-8",
            dataType: "html",
            data: {},
            success: function(data, textStatus, jqXHR){
                $("#id_row_modal").children().replaceWith(data);
                $("#"+$(element).attr("id")+"_modal").modal();
            },
            error: function(jqXHR, textStatus, errorThrown){
                console.log("error >>> " + textStatus);
            }
        }).done(function(){
            console.log("done");
        });
    });
    $("#id_project_create, #id_team_create, #id_work_create, #id_portfolio_create").click(function(event){
        event.preventDefault();
        var element = this;
        $.ajax({
            method: "GET",
            url: $(this).attr("href"),
            contextType: "application/json; charset=utf-8",
            dataType: "html",
            data: {},
            success: function(data, textStatus, jqXHR){
                $("#id_row_modal").children().replaceWith(data);
                $("#"+$(element).attr("id")+"_modal").modal();
            },
            error: function(jqXHR, textStatus, errorThrown){
                console.log("error >>> " + textStatus);
            }
        }).done(function(){
            console.log("done");
        });
    });
</script>
{% endblock %}