accounts/urls.py
from django.urls import path
from django.contrib import auth

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('search/', views.search, name='search'),
    #path('<username>/', views.detail, name='detail'),
    path('join/<username>/', views.join_group, name='join'),
    path('groups/<username>/', views.groups, name='groups'),
    path('password_change/', views.password_change, name='password_change'),
    #path('password/reset/', auth.views.password_reset, {'post_reset_redirect': '/password/reset/done/'}, name='password_reset'),
    #path('password/reset/done/', auth.views.password_reset_done),
    #path('password/reset/<uid36>[0-9A-Za-z]+)-<token>.+)/', auth.views.password_reset_confirm, {'post_reset_redirect': '/password/done/'}, name='password_reset_confirm'),
    #path('password/done/', auth.views.password_reset_complete),
    path('friend/<username>/list/', views.FriendList.as_view(), name='friend.list'),
    path('friend/<username>/for_list/', views.FriendForList.as_view(), name='friend.list_for'),
    path('friend/<username>/create/', views.FriendCreate.as_view(), name='friend.create'),
    path('friend/<username>/<pk>/', views.FriendDetail.as_view(), name='friend.detail'),
    path('friend/<username>/<pk>/update/', views.FriendUpdate.as_view(), name='friend.update'),
    path('friend/<username>/<pk>/delete/', views.FriendDelete.as_view(), name='friend.delete'),
    path('profile/list/', views.ProfileList.as_view(), name='profile.list'),
    path('profile/<username>/', views.ProfileDetail.as_view(), name='profile.detail'),
    path('profile/<username>/update/', views.ProfileUpdate.as_view(), name='profile.update'),
    path('profile/<username>/friend/', views.profile_toggle_friend, name='profile.friend'),
    path('profile/<username>/credit/', views.profile_toggle_credit, name='profile.credit'),
]

common/urls.py
from django.urls import path
from . import views


app_name = 'common'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('contact/thanks/', views.contact, name='thanks'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('logout/', views.logout, name='logout'),
    path('password_change/', views.password_change, name='password_change'),
]

job/urls.py
from django.urls import path

from . import views

app_name = 'job'

urlpatterns = [
    path('', views.index, name='index'),
    path('work/tile/', views.WorkTile.as_view(), name='work.tile'),
    path('work/user/', views.WorkUser.as_view(), name='work.user'),
    path('work/create/', views.WorkCreate.as_view(), name='work.create'),
    path('work/<pk>/', views.WorkDetail.as_view(), name='work.detail'),
    path('work/<pk>/update/', views.WorkUpdate.as_view(), name='work.update'),
    path('work/<pk>/delete/', views.WorkDelete.as_view(), name='work.delete'),
    path('portfolio/<pk>/friend/', views.work_toggle_friend, name='work.friend'),
    path('portfolio/<pk>/bookmark/', views.work_toggle_bookmark, name='work.bookmark'),
    path('portfolio/<pk>/apply/', views.work_toggle_apply, name='work.apply'),
    path('portfolio/<pk>/share/', views.work_toggle_share, name='work.share'),
    path('work/<pk>/comment/create/', views.CommentCreate.as_view(), name='comment.create'),
    path('work/<work_pk>/comment/<pk>/delete/', views.CommentDelete.as_view(), name='comment.delete'),
]

myartworks/urls.py
from django.conf.urls.static import static
from django.urls import path
from django.conf import settings
from django.urls import include
from django.contrib import admin


urlpatterns = [
    path('', include(('common.urls', 'common'), namespace='common')),
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('classification/', include(('classification.urls', 'classification'), namespace='classification')),
    path('gallery/', include(('gallery.urls', 'gallery'), namespace='gallery')),
    path('job/', include(('job.urls', 'job'), namespace='job')),
    path('messagebox/', include(('messagebox.urls', 'messagebox'), namespace='messagebox')),
    path('resume/', include(('resume.urls', 'resume'), namespace='resume')),
    path('group/', include(('group.urls', 'group'), namespace='group')),
    path('organization/', include(('organization.urls', 'organization'), namespace='organization')),
]

urlpatterns += [
    path('search/', include(('haystack.urls', 'haystack'), namespace='search')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Error page
handler400 = 'common.views.handler400'
handler403 = 'common.views.handler403'
handler404 = 'common.views.handler404'
handler405 = 'common.views.handler405'
handler500 = 'common.views.handler500'

common/models.py
from django.db import models

# Create your models here.

common/forms.py
from django import forms

from core.widgets import BootstrapEmailInput, BootstrapTextInput, BootstrapTextarea


class ContactForm(forms.Form):
    from_email = forms.EmailField(widget=BootstrapEmailInput(placeholder='From'))
    subject = forms.CharField(widget=BootstrapTextInput(placeholder='Subject'))
    message = forms.CharField(widget=BootstrapTextarea(placeholder='Message'), required=False)

common/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.shortcuts import render, redirect


from .forms import ContactForm


def index(request):
    """
    Index
    """
    # context = {}
    # return render(request, 'common/index.html', context)

    return redirect('gallery:portfolio.tile')

    # if request.user is not None:
    #     return redirect('accounts:profile.detail', username=request.user.username)
    # else:
    #     return redirect('gallery:portfolio.user')


def about(request):
    return render(request, 'common/about.html')


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, ['playanetworks@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('common:thanks')
    else:
        form = ContactForm()
    return render(request, "common/contact.html", {'form': form})


def thanks(request):
    message = 'Thank you for your message.'
    return render(request, "common/thanks.html", {'message': message})


def privacy(request):
    """
    Privacy Policy

    """
    return render(request, 'common/privacy.html')


def terms(request):
    """
    Terms of Us
    """
    return render(request, 'common/terms.html')


def logout(request):
    """
    Logout
    """
    return render(request, 'common/logout.html', {})


def password_change(request):
    """
    Password Change
    """
    return render(request, 'common/password_change.html', {})


def handler400(request):
    """
    HTTP Error 404 Bad request
    """
    return HttpResponse('<h1>HTTP Error 400 Bad request</h1>', {})


def handler403(request):
    """
    HTTP Error 403 Forbidden
    """
    return HttpResponse('<h1>HTTP Error 403 Forbidden.</h1>', {})


def handler404(request):
    """
    HTTP Error 404 Not Found
    """
    return HttpResponse('<h1>HTTP Error 404 Not Found</h1>', {})


def handler404(request):
    """
    HTTP Error 405 Method Not Allowed
    """
    return HttpResponse('<h1>HTTP Error 405 Method not allowed</h1>', {})


def handler500(request):
    """
    HTTP Error 500 Internal Server Error
    """
    return HttpResponse('<h1>HTTP Error 500 Internal server error</h1>', {})

common/templates/common/about.html
{% extends "common/base_site.html" %}
{% load i18n static %}{% load humanize %}


{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}"/>
{% endblock %}

{% block content_title %}<h1>{% trans 'About Us' %}</h1>{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-6" align="center">
        <h1><a href="http://playanetworks.com" target="_blank">{% trans 'MyArtworks' %}</a></h1>
        <h2>{% trans 'PlayaNetworks' %}</h2>
        <p>M{% trans 'MyArtworks' %}를 운영합니다.</p>
        <ul class="list-inline social-buttons">
            <li><a href="https://twitter.com/playa_networks/" target="_blank"><i class="fa fa-twitter fa-fw fa-2x"></i></a></li>
            <li><a href="https://www.facebook.com/playanetworks/" target="_blank"><i class="fa fa-facebook fa-fw fa-2x"></i></a></li>
            <li><a href="https://www.instagram.com/playa_networks/" target="_blank"><i class="fa fa-instagram fa-fw fa-2x"></i></a></li>
            <li><a href="https://github.com/playanetworks" target="_blank"><i class="fa fa-github fa-fw fa-2x"></i></a></li>
        </ul>
    </div>
</div><!-- /.row -->

<h2>{% trans 'Our Team' %}</h2>
<hr>
<div class="row">
    <div class="col-lg-6" align="center">
        <a href="http://mingyuchoo.com" target="_blank"><img class="img-circle" src="{% static 'common/img/mingyuchoo.jpg' %}" alt="Mingyu Choo" width="140" height="140"></a>
        <h2>{% trans 'Mingyu Choo' %}</h2>
        <p>{% trans 'MyArtworks' %}를 만들었습니다.</p>
        <ul class="list-inline social-buttons">
            <li><a href="https://twitter.com/mingyuchoo/" target="_blank"><i class="fa fa-twitter fa-fw fa-2x"></i></a></li>
            <li><a href="https://www.facebook.com/mingy.uchoo.9/" target="_blank"><i class="fa fa-facebook fa-fw fa-2x"></i></a></li>
            <li><a href="https://www.instagram.com/mingyu_choo/" target="_blank"><i class="fa fa-instagram fa-fw fa-2x"></i></a></li>
            <li><a href="https://github.com/mingyuchoo" target="_blank"><i class="fa fa-github fa-fw fa-2x"></i></a></li>
        </ul>
    </div>
</div><!-- /.row -->
<hr>
{% endblock %}

common/templates/common/base_site.html
{% extends "common/base.html" %}
{% load i18n static %}{% load humanize %}


{% block title %}{{ title|default:_('Home') }} | {{ site_title|default:_('MyArtworks') }}{% endblock %}

common/templates/common/contact.html
{% extends "common/base_site.html" %}
{% load i18n static %}{% load humanize %}


{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}"/>
{% endblock %}

{% block content_title %}<h1>{% trans 'Contact Us' %}</h1>{% endblock %}

{% block content %}
<p>개발 중입니다.</p>
{% endblock %}

common/templates/common/logout.html
{% extends "common/base_site.html" %}
{% load i18n static %}{% load humanize %}


{% block content_title %}
<h1>Are you sure?</h1>
{% endblock %}

{% block content %}
< a href="{% url 'accounts:logout' %}'>{% trans 'Yes' %}</a>
{% endblock %}

common/templates/common/password_change.html
{% extends "common/base_site.html" %}
{% load i18n static %}{% load humanize %}

{% block content_title %}
<h1>Password change</h1>
{% endblock %}

{% block content %}
<div><a href="{% url 'common:index %}">{% trans 'Index' %}</a></div>
<p>Thanks for spending some quality time with the web site today.</p>
<p><a href="{% url 'accounts:login' %}">{% trans 'Log in again' %}</a></p>
{% endblock %}

common/templates/common/privacy.html
{% extends "common/base_site.html" %}
{% load i18n static %}{% load humanize %}


{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}" />
{% endblock %}

{% block content_title %}<h1>{% trans 'Privacy Policy' %}</h1>{% endblock %}

{% block content %}
<p>개발 중입니다.</p>
{% endblock %}

common/templates/common/terms.html
{% extends "common/base_site.html" %}
{% load i18n static %}{% load humanize %}


{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}" />
{% endblock %}

{% block content_title %}<h1>{% trans 'Terms of Us' %}</h1>{% endblock %}

{% block content %}
<p>개발 중입니다.</p>
{% endblock %}

common/templates/common/thanks.html
{% extends "common/base_site.html" %}
{% load i18n static %}{% load humanize %}


{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}"/>
{% endblock %}

{% block content_title %}<h1>{% trans 'Contact Us' %}</h1>{% endblock %}

{% block content %}
{{ message }}
{% endblock %}