job/urls.py
from django.urls import path

from . import views

app_name = 'job'

urlpatterns = [
    path('', views.index, name='index'),
    path('work/tile/', views.WorkTile.as_view(), name='work.tile'),
    path('work/user/', views.WorkUser.as_view(), name='work.user'),
    path('work/create/', views.WorkCreate.as_view(), name='work.create'),
    path('work/<pk>/', views.WorkDetail.as_view(), name='work.detail'),
    path('work/<pk>/update/', views.WorkUpdate.as_view(), name='work.update'),
    path('work/<pk>/delete/', views.WorkDelete.as_view(), name='work.delete'),
    path('portfolio/<pk>/friend/', views.work_toggle_friend, name='work.friend'),
    path('portfolio/<pk>/bookmark/', views.work_toggle_bookmark, name='work.bookmark'),
    path('portfolio/<pk>/apply/', views.work_toggle_apply, name='work.apply'),
    path('portfolio/<pk>/share/', views.work_toggle_share, name='work.share'),
    path('work/<pk>/comment/create/', views.CommentCreate.as_view(), name='comment.create'),
    path('work/<work_pk>/comment/<pk>/delete/', views.CommentDelete.as_view(), name='comment.delete'),
]

myartworks/urls.py
from django.conf.urls.static import static
from django.urls import path
from django.conf import settings
from django.urls import include
from django.contrib import admin


urlpatterns = [
    path('', include(('common.urls', 'common'), namespace='common')),
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('classification/', include(('classification.urls', 'classification'), namespace='classification')),
    path('gallery/', include(('gallery.urls', 'gallery'), namespace='gallery')),
    path('job/', include(('job.urls', 'job'), namespace='job')),
    path('messagebox/', include(('messagebox.urls', 'messagebox'), namespace='messagebox')),
    path('resume/', include(('resume.urls', 'resume'), namespace='resume')),
    path('group/', include(('group.urls', 'group'), namespace='group')),
    path('organization/', include(('organization.urls', 'organization'), namespace='organization')),
]

urlpatterns += [
    path('search/', include(('haystack.urls', 'haystack'), namespace='search')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Error page
handler400 = 'common.views.handler400'
handler403 = 'common.views.handler403'
handler404 = 'common.views.handler404'
handler405 = 'common.views.handler405'
handler500 = 'common.views.handler500'

organization/urls.py
from django.urls import path

from . import views


app_name = 'organization'

urlpatterns = [
    path('team/tile/', views.TeamTile.as_view(), name='team.tile'),
    path('team/user/', views.TeamUser.as_view(), name='team.user'),
    path('team/create/', views.TeamCreate.as_view(), name='team.create'),
    path('team/<pk>/', views.TeamDetail.as_view(), name='team.detail'),
    path('team/<pk>/update/', views.TeamUpdate.as_view(), name='team.update'),
    path('team/<pk>/delete/', views.TeamDelete.as_view(), name='team.delete'),
    path('team/<pk>/bookmark/', views.team_toggle_bookmark, name='team.bookmark'),
    path('team/<pk>/apply/', views.team_toggle_apply, name='team.apply'),
    path('team/<pk>/share/', views.team_toggle_share, name='team.share'),
    # path('team/<pk>/membership/list/', views.MembershipList.as_view(), name='membership.list'),
    # path('team/<team_pk>/membership/<pk>/', views.MembershipDetail.as_view(), name='membership.detail'),
    path('team/<team_pk>/membership/<pk>/update/', views.MembershipUpdate.as_view(), name='membership.update'),
    # path('team/<team_pk>/membership/<pk>/delete/', views.MembershipDelete.as_view(), name='membership.delete'),
    path('team/<pk>/comment/create/', views.CommentCreate.as_view(), name='comment.create'),
    path('team/<team_pk>/comment/<pk>/delete/', views.CommentDelete.as_view(), name='comment.delete'),
]

organization/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from classification.models import Category

from taggit.managers import TaggableManager


class Team(models.Model):
    """
    Team class
    """
    STATUS = (
        ('O', 'Open'),
        ('C', 'Closed'),
    )
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=5120)
    leader = models.ForeignKey(User, related_name='organization_team_leaders', on_delete=models.DO_NOTHING)
    member = models.ManyToManyField(User, through='Membership')
    status = models.CharField(max_length=1, choices=STATUS, default='O')
    writer = models.ForeignKey(User, related_name='organization_teams', on_delete=models.DO_NOTHING)
    created_time = models.DateTimeField(auto_now_add=True)
    updated_time = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category)
    comment_count = models.IntegerField(default=0)
    bookmark_count = models.IntegerField(default=0)
    apply_count = models.IntegerField(default=0)
    share_count = models.IntegerField(default=0)
    tags = TaggableManager()

    class Meta:
        pass

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('organization:team.user')

    def categories(self):
        return ", ".join([category.name for category in self.category.all()])


class Membership(models.Model):
    """
    Membership class (Team-M2M-User)
    """
    STATUS = (
        ('R', 'Request'),
        ('D', 'Denied'),
        ('A', 'Approved'),
    )
    team = models.ForeignKey(Team, on_delete=models.DO_NOTHING)
    member = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='organization_team_members')
    status = models.CharField(max_length=1, choices=STATUS, default='R')
    updated_time = models.DateTimeField(auto_now_add=True)
    requested_date = models.DateField(auto_now_add=True)
    joined_date = models.DateField(null=True)

    class Meta:
        pass

    def get_absolute_url(self):
        return reverse('organization:team.detail', kwargs={'pk': str(self.team.pk)})

    def __str__(self):
        return "{}:{}-{}".format(self.id, self.team.name, self.member.username)


class Comment(models.Model):
    """
    Comment class
    """
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    writer = models.ForeignKey(User, related_name='team_comments', on_delete=models.DO_NOTHING)
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        pass

    def __str__(self):
        return "{}".format(self.id)

    def get_absolute_url(self):
        return reverse('organization:team.detail', kwargs={'pk': str(self.team.pk)})

    def save(self, *args, **kwargs):
        super(Comment, self).save(*args, **kwargs)


class Bookmark(models.Model):
    """
    Bookmark class
    """
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    writer = models.ForeignKey(User, related_name='team_bookmarks', on_delete=models.DO_NOTHING)
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        pass

    def __str__(self):
        return "{}".format(self.id)

    def get_absolute_url(self):
        return reverse('organization:team.detail', kwargs={'pk': str(self.team.pk)})

    def save(self, *args, **kwargs):
        super(Bookmark, self).save(*args, **kwargs)


class Apply(models.Model):
    """
    Apply class
    """
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    writer = models.ForeignKey(User, related_name='team_applies', on_delete=models.DO_NOTHING)
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        pass

    def __str__(self):
        return "{}".format(self.id)

    def get_absolute_url(self):
        return reverse('organization:team.detail', kwargs={'pk': str(self.team.pk)})

    def save(self, *args, **kwargs):
        super(Apply, self).save(*args, **kwargs)


class Share(models.Model):
    """
    Share class
    """
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    writer = models.ForeignKey(User, related_name='team_shares', on_delete=models.DO_NOTHING)
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        pass

    def __str__(self):
        return "{}".format(self.id)

    def get_absolute_url(self):
        return reverse('organization:team.detail', kwargs={'pk': str(self.team.pk)})

    def save(self, *args, **kwargs):
        super(Share, self).save(*args, **kwargs)

job/views.py
import logging
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import resolve, reverse_lazy
from django.shortcuts import get_object_or_404, redirect
from django.utils.translation import ugettext_lazy as _
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from core.mixins import WriterOnlyMixin

from accounts.models import Friend

from .models import Work, Comment, Bookmark, Apply, Share
from .forms import WorkCreateForm, WorkUpdateForm, CommentForm


logger = logging.getLogger(__name__)


def index(request):
    return redirect('job:work.tile')


class WorkTile(LoginRequiredMixin, ListView):
    """
    Retrieve Work List
    """
    model = Work
    context_object_name = 'work_list'
    http_method_names = ['get']
    template_name = 'job/work_list_tile.html'
    paginate_by = 9

    def get_queryset(self):
        work_list = Work.objects.all().order_by('-created_time')
        return work_list

    def get_context_data(self, **kwargs):
        context = super(WorkTile, self).get_context_data(**kwargs)
        context['title'] = _(resolve(self.request.path).app_name.capitalize())

        return context


class WorkUser(LoginRequiredMixin, ListView):
    """
    Retrieve Work List
    """
    model = Work
    context_object_name = 'work_list'
    http_method_names = ['get']
    template_name = 'job/work_list_user.html'
    paginate_by = 9

    def get_queryset(self):
        work_list = Work.objects.filter(writer=self.request.user).order_by('-created_time')
        return work_list

    def get_context_data(self, **kwargs):
        context = super(WorkUser, self).get_context_data(**kwargs)
        context['title'] = _(resolve(self.request.path).app_name.capitalize())
        context['work_form'] = WorkCreateForm
        context['comment_form'] = CommentForm

        return context


class WorkCreate(LoginRequiredMixin, CreateView):
    """
    Create Work
    """
    model = Work
    form_class = WorkCreateForm
    http_method_names = ['get', 'post', ]
    template_name = 'job/work_form_create.html'
    success_url = reverse_lazy('job:work.tile')

    def form_valid(self, form):
        work = form.save(commit=False)
        work.writer = self.request.user
        work.save()
        form.save_m2m()
        messages.success(self.request, _('Your work was created successfully.'))
        return super(WorkCreate, self).form_valid(form)

    def form_invalid(self, form):
        return super(WorkCreate, self).form_invalid(form)

    def get_success_url(self):
        return reverse_lazy('accounts:profile.detail', args=(self.request.user.username,))


class WorkDetail(LoginRequiredMixin, DetailView):
    """
    Detail Work
    """
    model = Work
    context_object_name = 'work'
    http_method_names = ['get']

    def get_context_data(self, **kwargs):
        context = super(WorkDetail, self).get_context_data(**kwargs)
        context['comment_form'] = CommentForm
        return context


class WorkUpdate(WriterOnlyMixin, UpdateView):
    """
    Update Work
    """
    model = Work
    form_class = WorkUpdateForm
    context_object_name = 'work'
    http_method_names = ['get', 'post', ]
    template_name = 'job/work_form_update.html'

    def form_valid(self, form):
        work = form.save(commit=False)
        work.writer = self.request.user
        work.save()
        form.save_m2m()
        messages.success(self.request, _('Your work was updated successfully.'))
        return super(WorkUpdate, self).form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, _('Your work was not updated!'))
        return super(WorkUpdate, self).form_invalid(form)


class WorkDelete(WriterOnlyMixin, DeleteView):
    """
    Delete Work
    """
    model = Work
    context_object_name = 'work'
    http_method_names = ['get', 'post']
    success_url = reverse_lazy('job:work.tile')


def work_toggle_friend(request, **kwargs):
    context = {}
    request_user = User.objects.get(pk=request.user.pk)
    work = Work.objects.get(pk=kwargs["pk"])
    try:
        friend = Friend.objects.get(writer=request_user, friend=work.writer)
        friend.delete()
        context['class'] = 'fa fa-chain-broken'
    except Friend.DoesNotExist:
        friend = Friend(writer=request_user, friend=work.writer)
        friend.save()
        context['class'] = 'fa fa-link'
    return JsonResponse(context)


def work_toggle_bookmark(request, **kwargs):
    context = {}
    work = Work.objects.get(pk=kwargs["pk"])
    writer = User.objects.get(pk=request.user.pk)
    try:
        bookmark = Bookmark.objects.get(work=work, writer=writer)
        bookmark.delete()
        if work.bookmark_count > 0:
            work.bookmark_count -= 1
            work.save()
        context['class'] = 'fa fa-bookmark-o'
    except Bookmark.DoesNotExist:
        bookmark = Bookmark(work=work, writer=writer)
        bookmark.save()
        work.bookmark_count += 1
        work.save()
        context['class'] = 'fa fa-bookmark'
    context['count'] = work.bookmark_count
    context['span'] = ''.join(['#', 'badge-bookmark-', str(work.pk)])
    return JsonResponse(context)


def work_toggle_apply(request, **kwargs):
    context = {}
    work = Work.objects.get(pk=kwargs["pk"])
    writer = User.objects.get(pk=request.user.pk)
    try:
        apply = Apply.objects.get(work=work, writer=writer)
        apply.delete()
        if work.apply_count > 0:
            work.apply_count -= 1
            work.save()
        context['class'] = 'fa fa-flag-o'
    except Apply.DoesNotExist:
        apply = Apply(work=work, writer=writer)
        apply.save()
        work.apply_count += 1
        work.save()
        context['class'] = 'fa fa-flag'
    context['count'] = work.apply_count
    context['span'] = ''.join(['#', 'badge-apply-', str(work.pk)])
    return JsonResponse(context)


def work_toggle_share(request, **kwargs):
    context = {}
    work = Work.objects.get(pk=kwargs["pk"])
    writer = User.objects.get(pk=request.user.pk)
    try:
        share = Share.objects.get(work=work, writer=writer)
        share.delete()
        if work.share_count > 0:
            work.share_count -= 1
            work.save()
        context['class'] = 'fa fa-share-square-o'
    except Share.DoesNotExist:
        share = Share(work=work, writer=writer)
        share.save()
        work.share_count += 1
        work.save()
        context['class'] = 'fa fa-share-square'
    context['count'] = work.share_count
    context['span'] = ''.join(['#', 'badge-share-', str(work.pk)])
    return JsonResponse(context)


class CommentList(LoginRequiredMixin, ListView):
    """
    Comment List
    """
    model = Comment
    context_object_name = 'comment_list'
    http_method_names = ['get']
    paginate_by = 9

    def get_queryset(self):
        comment_list = Comment.objects.all().order_by('-created_time')
        return comment_list

    def get_context_data(self, **kwargs):
        context = super(CommentList, self).get_context_data(**kwargs)
        work = get_object_or_404(Work, pk=self.kwargs.get('pk'))
        context['work'] = work
        return context


class CommentCreate(LoginRequiredMixin, CreateView):
    """
    Create Comment
    """
    model = Comment
    form_class = CommentForm
    http_method_names = ['get', 'post', ]
    template_name = 'job/comment_form.html'

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.work = get_object_or_404(Work, pk=self.kwargs.get('pk'))
        comment.writer = self.request.user
        comment.save()
        messages.success(self.request, _('Your comment was created successfully.'))
        return super(CommentCreate, self).form_valid(form)

    def form_invalid(self, form):
        return super(CommentCreate, self).form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super(CommentCreate, self).get_context_data(**kwargs)
        work = get_object_or_404(Work, pk=self.kwargs.get('pk'))
        context['work'] = work
        return context


class CommentDelete(WriterOnlyMixin, DeleteView):
    """
    Delete Comment
    """
    model = Comment
    http_method_names = ['get', 'post']

    def get_success_url(self):
        return reverse_lazy('job:work.detail', args=(self.object.work.id,))

    def delete(self, request, *args, **kwargs):
        messages.success(request, _('Your comment was deleted successfully.'))
        return super(CommentDelete, self).delete(request, *args, **kwargs)

organization/templates/organization/team_detail.html
{% extends "organization/base_site.html" %}
{% load i18n static %}{% load humanize %}
{% load organization_filters %}
{% load widget_tweaks %}
{% load gallery_filters %}

{% block content %}
    <h2>{{ team.name }}
<span class="text-muted">
{% if user.is_authenticated %}
    {#    {% if team.writer != request.user %}#}
    {#    <a href ="{% url 'organization:team.friend' pk=team.pk %}"><i class="{% is_friend team username=request.user.username %}" aria-hidden="true" id="i-friend-{{ team.pk }}"></i></a>#}
    {#    {% endif %}#}
    {% if team.writer.profile.status == 'A' %}
        &nbsp;<i class="fa fa-unlock" aria-hidden="true"></i>
    {% else %}
        &nbsp;<i class="fa fa-lock" aria-hidden="true"></i>
    {% endif %}
{% endif %}
    <a href="{% url 'accounts:profile.detail' username=team.writer.username %}">{{ team.writer }}</a> on {{ team.created_time|naturaltime }}
    {% if user.is_authenticated and team.writer == request.user %}
        &nbsp;<a href="{% url 'organization:team.update' pk=team.id %}" id="id_team_update"><i class="fa fa-cog"
                                                                                                 aria-hidden="true"
                                                                                                 id="i-update-{{ team.pk }}"></i></a>
        &nbsp;<a href="{% url 'organization:team.delete' pk=team.id %}" id="id_team_delete"><i class="fa fa-trash"
                                                                                                 aria-hidden="true"
                                                                                                 id="i-delete-{{ team.pk }}"></i></a>
    {% endif %}<br/>
</span>
    </h2>
    <hr class="featurette-divider">
    <div class="row featurette">
        <div class="col-lg-6">
            <p>
                {{ team.categories }}<br/>
                {{ team.description|linebreaks }}
                {% for tag in team.tags.all %}
                    {{ tag.name }}
                {% empty %}
                {% endfor %}
            </p>
            <p>
                &nbsp;&nbsp;<i class="{% has_team_comment team username=request.user.username %}" aria-hidden="true"></i><span class="badge" id="badge-comment-{{ team.pk }}">{{ team.comment_set.all|length }}</span>
                &nbsp;&nbsp;<a href="{% url 'organization:team.bookmark' pk=team.pk %}"><i class="{% has_team_bookmark team username=request.user.username %}" aria-hidden="true"></i></a> <span class="badge" id="badge-bookmark-{{ team.pk }}">{{ team.bookmark_count }}</span>
                &nbsp;&nbsp;<a href="{% url 'organization:team.apply' pk=team.pk %}"><i class="{% has_team_apply team username=request.user.username %}" aria-hidden="true"></i></a> <span class="badge" id="badge-apply-{{ team.pk }}">{{ team.apply_count }}</span>
                &nbsp;&nbsp;<a href="{% url 'organization:team.share' pk=team.pk %}"><i class="{% has_team_share team username=request.user.username %}" aria-hidden="true"></i></a> <span class="badge" id="badge-share-{{ team.pk }}">{{ team.share_count }}</span>
            </p>
            <hr class="featurette-divider">
            {% if user.is_authenticated %}
                <form class="form-horizontal" action="{% url 'organization:comment.create' pk=team.pk %}"
                      method="post" enctype="multipart/form-data" id="form-comment">
                    {% csrf_token %}
                    <div class="{% if comment_form.content.errors %}has-error{% endif %}" id="id_div_content">
                        {{ comment_form.content }}
                    </div>
                </form>
            {% endif %}<br/>
            {% for comment in team.comment_set.all %}
                <a href="{% url 'accounts:profile.detail' username=comment.writer.username %}">{{ comment.writer.username }}</a>
                {{ comment.content }}
                {% if comment.writer == request.user %}
                    &nbsp;<a href="{% url 'organization:comment.delete' team_pk=team.pk pk=comment.pk %}"
                             id="id_team_comment_delete"><i class="fa fa-trash" aria-hidden="true"></i></a>
                {% endif %}
                <br/>
            {% empty %}
                <p class="text-muted"><i>No comment exists yet.</i></p>
            {% endfor %}
        </div>
        <div class="col-lg-6">
            <div class="row">
                <div class="col-lg-offset-1 col-lg-5">
                    <img class="img-circle" src="{{ team.writer.profile.picture.url }}"
                         alt="{{ team.wirter.username }}" width="140" height="140">
                    <h2>
                        <a href="{% url 'accounts:profile.detail' username=team.writer.username %}">{{ team.writer }}</a>
                    </h2>
                </div>
                <div class="col-lg-5">
                    {{ team.writer.profile.bio|linebreaks }}
                    <p><a class="btn btn-default"
                          href="{% url 'accounts:profile.detail' username=team.writer.username %}" role="button">View
                        details &raquo;</a></p>
                </div>
            </div>
            <div class="row">
                {% if user == team.writer or has_membership %}
                    <hr class="featurette-divider">
                    <table class="table table-striped table-hover ">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>{% trans 'User' %}</th>
                            <th>{% trans 'Status' %}</th>
                            <th>{% trans 'Requested Date' %}</th>
                            <th>{% trans 'Joined Date' %}</th>
                            <th>{% trans 'Update' %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for membership in membership_list %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>
                                    <a href="{% url 'accounts:profile.detail' username=membership.member.username %}">{{ membership.member.username }}</a>
                                </td>
                                <td>{{ membership.get_status_display }}</td>
                                <td>{{ membership.requested_date }}</td>
                                <td>{% if membership.joined_date %}{{ membership.joined_date }}{% endif %}</td>
                                <td>
                                    <a href="{% url 'organization:membership.update' team_pk=membership.team.pk pk=membership.pk %}"
                                       class="btn btn-link" id="id_team_membership_update">{% trans 'Update' %}</a>
                                </td>
                            </tr>
                        {% empty %}
                        {% endfor %}
                        </tbody>
                    </table>
                {% endif %}
            </div>
        </div>
    </div>

    <hr class="featurette-divider">
    {% if user == team.writer %}
        <a href="{% url 'gallery:portfolio.create_for_team' team_pk=team.pk %}" class="btn btn-default btn-lg btn-block" id="id_portfolio_create">
            <i class="fa fa-plus" aria-hidden="true"></i> {% trans 'Create Team Portfolio' %}
        </a><br/>
    {% endif %}

    {% for portfolio in portfolio_list %}
    {% if forloop.counter0|divisibleby:3 %}
    <!-- Content Row -->
    <div class="row">
    {% endif %}
        <div class="col-lg-4">
            <div class="list-organization">
                <a href="{% url 'gallery:portfolio.detail' pk=portfolio.pk %}" class="list-organization-item">
                    <h4 class="list-organization-item-heading">
                        <img src="{{ portfolio.image.url }}" alt="{{ portfolio.title }}" width="100%">
                    </h4>
                    <p class="list-organization-item-text">
                        {{ portfolio.description|linebreaks }}
                        <small>by {{ portfolio.writer }} on {{ portfolio.created_time|naturaltime }}</small><br/>
                        <span class="badge" id="badge-comment-{{ portfolio.pk }}"><i class="{% has_portfolio_comment portfolio username=request.user.username %}" aria-hidden="true"></i> {{ portfolio.comment_set.all|length }}</span>
                        <span class="badge" id="badge-apply-{{ portfolio.pk }}"><i class="{% has_portfolio_comment portfolio username=request.user.username %}" aria-hidden="true"></i> {{ portfolio.apply_count }}</span>
                        <span class="badge" id="badge-share-{{ portfolio.pk }}"><i class="{% has_portfolio_share portfolio username=request.user.username %}" aria-hidden="true"></i> {{ portfolio.share_count }}</span>
                    </p>
                </a>
            </div>
        </div>
        <!-- /.col-md-4 -->
        {% if forloop.counter|divisibleby:3 or forloop.last %}
    </div>
    <!-- /.row -->
    {% endif %}
    {% empty %}
    <p>{% trans 'No item exists yet.' %}</p>
    {% endfor %}


{% endblock %}

{% block extrascript %}
    <script type="text/javascript">
        $("i[id*='i-friend-']").click(function (event) {
            event.preventDefault();
            var element = this;
            $.ajax({
                method: "POST",
                url: $(this).parents().attr("href"),
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                data: {'csrfmiddlewaretoken': '{{ csrf_token }}'},
                success: function (data, textStatus, jqXHR) {
                    $(data.span).text(data.count);
                    $(element).removeClass();
                    $(element).addClass(data.class);
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.log("error >>> " + textStatus);
                }
            }).done(function () {
                console.log("done");
            });
        });

        $("p a i.fa").click(function (event) {
            event.preventDefault();
            var element = this;
            $.ajax({
                method: "POST",
                url: $(this).parents().attr("href"),
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                data: {'csrfmiddlewaretoken': '{{ csrf_token }}'},
                success: function (data, textStatus, jqXHR) {
                    $(data.span).text(data.count);
                    $(element).removeClass();
                    $(element).addClass(data.class);
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.log("error >>> " + textStatus);
                }
            }).done(function () {
                console.log("done");
            });
        });

        $("#form-comment").submit(function (event) {
            if (!$("#id_content").val()) {
                $("#id_content").attr("placeholder", "Type some contents here");
                $("#id_div_content").addClass("has-error");
                event.preventDefault();
            }
        });
        $("[id^='id_team'], #id_portfolio_create").click(function (event) {
            event.preventDefault();
            var element = this;
            $.ajax({
                method: "GET",
                url: $(this).attr("href"),
                contextType: "application/json; charset=utf-8",
                dataType: "html",
                data: {},
                success: function (data, textStatus, jqXHR) {
                    $("#id_row_modal").children().replaceWith(data);
                    $("#" + $(element).attr("id") + "_modal").modal();
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.log("error >>> " + textStatus);
                }
            }).done(function () {
                console.log("done");
            });
        });
    </script>
{% endblock %}

organization/templates/organization/team_form_create.html
{% load i18n static %}{% load humanize %}
{% load widget_tweaks %}
<div class="modal fade" role="dialog" id="id_team_create_modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="{% url 'organization:team.create' %}" method="post" enctype="multipart/form-data" id="id_form_create">
                {% csrf_token %}
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">{% trans 'Create Team' %}</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group {% if form.name.errors %}has-error{% endif %}">{{ form.name }}</div>
                    <div class="form-group {% if form.description.errors %}has-error{% endif %}">{{ form.description }}</div>
                    <div class="form-group {% if form.tags.errors %}has-error{% endif %}">{{ form.tags }}</div>
                </div>
                <div class="modal-footer">
                    <a class="btn btn-default" href="{% url 'organization:team.user' %}" data-dismiss="modal">
                        <i class="fa fa-times" aria-hidden="true"></i> {% trans 'Cancel' %}
                    </a>
                    <input class="btn btn-theme" type="submit" value="{% trans 'Submit' %}"/>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="{% static 'common/js/playanetworks.js' %}"></script>
<script type="text/javascript">
    $("#id_form_create").submit(function(event){
       if(!$("#id_name").val()) {
           $("#id_name").attr("placeholder", "Type some contents here");
           $("#id_name").parent().addClass("has-error");
           event.preventDefault();
       }
       if(!$("#id_description").val()) {
           $("#id_description").attr("placeholder", "Type some contents here");
           $("#id_description").parent().addClass("has-error");
           event.preventDefault();
       }
    });
</script>